config/routes.rb
Rails.application.routes.draw do
  resources :laptops
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "laptop" ,to:"laptop#index"
  get "mobile", to:"mobile#index"
  get "about", to:"about#index"
  root to:"home#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/laptop.rb
class Laptop < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
end

app/controllers/laptop_controller.rb
class LaptopController < ApplicationController
    def index
    end
    
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  before_action :set_laptop, only: %i[ show edit update destroy ]

  # GET /laptops or /laptops.json
  def index
    @laptops = Laptop.all
  end

  # GET /laptops/1 or /laptops/1.json
  def show
  end

  # GET /laptops/new
  def new
    @laptop = Laptop.new
  end

  # GET /laptops/1/edit
  def edit
  end

  # POST /laptops or /laptops.json
  def create
    @laptop = Laptop.new(laptop_params)

    respond_to do |format|
      if @laptop.save
        format.html { redirect_to laptop_url(@laptop), notice: "Laptop was successfully created." }
        format.json { render :show, status: :created, location: @laptop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laptops/1 or /laptops/1.json
  def update
    respond_to do |format|
      if @laptop.update(laptop_params)
        format.html { redirect_to laptop_url(@laptop), notice: "Laptop was successfully updated." }
        format.json { render :show, status: :ok, location: @laptop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laptop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laptops/1 or /laptops/1.json
  def destroy
    @laptop.destroy

    respond_to do |format|
      format.html { redirect_to laptops_url, notice: "Laptop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laptop
      @laptop = Laptop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def laptop_params
      params.require(:laptop).permit(:name, :price, :brand, :offfer)
    end
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>SmartBuy welcoms you to home page</h1>

app/views/laptop/index.html.erb
<h1>Laptops</h1>

app/views/laptops/_form.html.erb
<%= form_with(model: laptop) do |form| %>
  <% if laptop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(laptop.errors.count, "error") %> prohibited this laptop from being saved:</h2>

      <ul>
        <% laptop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :offfer, style: "display: block" %>
    <%= form.text_field :offfer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/laptops/_laptop.html.erb
<div class="card" style="width: 18rem;">
<img src="https://img1.gadgetsnow.com/gd/images/products/additional/large/G376926_View_1/computer-laptop/laptops/msi-gf63-11uc-850in-11th-gen-intel-core-i7-11800h-15-6-inches-gaming-laptop-8gb-512gb-ssd-windows-10-black-1-86-kg-.jpg" class="card-img-top" alt="...">

<div id="<%= dom_id laptop %>">
  <ul class="list-group list-group-flush">
  <p>
    <strong class="list-group-item">Name:
    <%= laptop.name %>
    </strong>
  </p>

  <p>
    <strong class="list-group-item">Price:
    <%= laptop.price %>
    </strong>
  </p>

  <p>
    <strong class="list-group-item">Brand:
    <%= laptop.brand %>
    </strong>
  </p>

  <p>
    <strong class="list-group-item">Offfer:
    <%= laptop.offfer %>
    </strong>
  </p>
 </ul>
</div>


</div>

app/views/laptops/edit.html.erb
<h1>Editing laptop</h1>

<%= render "form", laptop: @laptop %>

<br>

<div>
  <%= link_to "Show this laptop", @laptop %> |
  <%= link_to "Back to laptops", laptops_path %>
</div>

app/views/laptops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Laptops</h1>

<div id="laptops">
  <% @laptops.each do |laptop| %>
    <%= render laptop %>
    <p>
      <%= link_to "Show this laptop", laptop %>
    </p>
  <% end %>
</div>

<%= link_to "New laptop", new_laptop_path %>

app/views/laptops/new.html.erb
<h1>New laptop</h1>

<%= render "form", laptop: @laptop %>

<br>

<div>
  <%= link_to "Back to laptops", laptops_path %>
</div>

app/views/laptops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @laptop %>

<div>
  <%= link_to "Edit this laptop", edit_laptop_path(@laptop) ,class:"btn btn-dark"%> 
  <%= link_to "Back to laptops", laptops_path ,class:"btn btn-dark"%>

  <%= button_to "Destroy this laptop", @laptop, method: :delete ,class:"btn btn-danger"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartBuy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>

    <%= render partial:"shared/navbar"%>


    <%= yield %>



    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/mobile/index.html.erb
<h1>mobiles here </h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-secondary">
  <div class="container-fluid">
    <%= link_to "LOGO",root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Laptops" ,laptops_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Mobiles" ,mobile_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "About Us" ,about_path,class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>